export const projects = [
  {
    id: 1,
    title: "AOL Instant Messenger Revival",
    description: "A faithful, modern web re-creation of classic AIM with draggable windows, taskbar toggles, and nostalgic Windows XP styling.",
    type: "Personal",
    image: "/images/projects/aim/aim-thumb.jpg",
    link: "https://aim-revival.alissa.dev/",
    note: "Work-in-progress",
    screenshotType: "desktop",
    url: "aim-revival.alissa.dev",
    screenshots: ["/images/projects/aim/aim-1.png"],
    skills: ["React", "Next.js", "Tailwind CSS", "Firebase (Auth/Firestore)", "HTML", "CSS", "JavaScript", "Cursor", "Git", "Vercel"],
    details: [
      "This ongoing project recreates the look and feel of AOL Instant Messenger for the web. It includes a draggable Login window and Buddy List, a taskbar button that reflects active state and toggles visibility, and chat windows that currently pop out via window.open() to mimic classic AIM behavior.",
      "I built this project mostly out of nostalgia. AIM was such a huge part of my childhood and I just loved everything about it. Re-creating it now is my way of bringing back that classic experience I miss so much, while having fun experimenting with React, Next.js, and modern web tools.",
      "I use Cursor (AI-powered editor) to speed up development, generate snippets, and debug tricky UI behavior. Firebase (Auth + Firestore) is used for sign-in, presence, and message history. XP.css is used for the classic Windows XP styling.",
    ],
    highlights: [
      "Draggable windows with bounds-clamping to keep them on screen",
      "Buddy List → double-click opens chats in separate pop-out windows",
      "Window focus/stacking states (active window gets topmost z-index)",
      "Nostalgic UI details throughout",
      "Planned: Classic AIM sounds, emoticons, buddy icons and profiles",
    ],
  },
  {
    id: 2,
    title: "Parallels Desktop for Mac Product\xA0Pages",
    description: "Revamped product pages to align with Apple's design language, with scrollable modal pop-ups per use case.",
    type: "Work",
    image: "/images/projects/parallels/parallels-thumb.jpg",
    link: "https://www.parallels.com/products/desktop/",
    screenshotType: "desktop",
    url: "parallels.com/products/desktop/",
    screenshots: [
      "/images/projects/parallels/parallels-1.png",
      "/images/projects/parallels/parallels-2.png",
      "/images/projects/parallels/parallels-3.png",
    ],
    skills: ["HTML", "CSS", "JavaScript", "Bootstrap", "Django", "Git", "Jenkins"],
    details: [
      "This project involved revamping the product pages for Parallels Desktop 19 for Mac to make it more visually cohesive with the Apple website, by implementing scrollable modal pop-ups with information specific to each use case.",
    ],
  },
  {
    id: 3,
    title: "Weather App",
    description: "A fast, elegant weather app with city/ZIP search, geolocation, hourly and 7-day forecasts, unit toggles, and detailed conditions.",
    type: "Personal",
    image: "/images/projects/weather/weather-thumb.jpg",
    link: "https://weather.alissa.dev/",
    screenshotType: "weatherPhones",
    url: "weather.alissa.dev",
    phoneScreenshots: [
      { src: "/images/projects/weather/weather-brisbane.png", city: "Brisbane" },
      { src: "/images/projects/weather/weather-tokyo.png", city: "Tokyo" },
      { src: "/images/projects/weather/weather-broken-hill.png", city: "Broken Hill" },
      { src: "/images/projects/weather/weather-boston.png", city: "Boston" },
    ],
    skills: ["Next.js", "React", "Tailwind CSS", "OpenWeather One Call API", "Google Places Autocomplete", "Geolocation API", "JavaScript", "Git", "Vercel"],
    details: [
      "A clean, responsive weather app built with Next.js and Tailwind 4. Users can search by city or ZIP with Google Places Autocomplete, or simply allow geolocation to fetch local conditions instantly.",
      "The app displays current conditions, hourly and 7-day forecasts, dew point, UV index, humidity, pressure, wind, and sunrise/sunset - along with a F°/C° toggle and a full moon-phase system that maps numeric phases to readable labels and SVGs.",
      "The UI dynamically adapts to both time of day and current conditions - a clear night looks different from a cloudy one, a sunny afternoon different from an overcast morning. Designed mobile-first - it looks clean on desktop too, just don't expect it to fill the whole screen.",
    ],
    highlights: [
      "Geolocation detection for instant local weather",
      "Search with Google Places Autocomplete (city or ZIP)",
      "OpenWeather One Call: current, hourly, 7-day forecasts",
      "Unit toggle between Celsius and Fahrenheit",
      "Moon phase mapping - readable labels and custom SVG icons",
      "Time-of-day gradient system",
      "Mobile-first UX",
    ],
  },
  {
    id: 4,
    title: "Alludo Website",
    description: "Built various pages during a major corporate rebrand, including an animated homepage that shifts with time of day.",
    type: "Work",
    image: "/images/projects/alludo/alludo-thumb.jpg",
    link: "https://web.archive.org/web/20250222033511/https://www.alludo.com/en/",
    screenshotType: "desktop",
    url: "alludo.com",
    screenshots: [
      "/images/projects/alludo/alludo-1.png",
      "/images/projects/alludo/alludo-2.png",
      "/images/projects/alludo/alludo-3.png",
    ],
    skills: ["HTML", "CSS", "Bootstrap", "JavaScript", "Git", "Jenkins"],
    details: [
      "After a major corporate rebranding, I was tasked with building out various pages of the Alludo company website, including the homepage, which features a series of animations as you scroll down the page. These animations were built with CSS keyframes.",
      "The images and color gradient in the hero also change depending on the time of day you view the site.",
    ],
    highlights: [
      "Time-of-day hero: different imagery and gradients for morning, afternoon, and night",
      "Scroll-triggered CSS keyframe animations throughout the homepage",
      "Built as part of a full company rebrand from Corel to Alludo",
    ],
  },
  {
    id: 5,
    title: "Farm Website",
    description: "Responsive website refresh for a local farm, bringing appearance and functionality up to date for mobile users.",
    type: "Freelance",
    image: "/images/projects/farm/farm-thumb.jpg",
    link: null,
    github: "https://github.com/avbengt/cold-spring-brook-farm",
    screenshotType: "mixed",
    url: "farmwebsite.com",
    desktopScreenshot: "/images/projects/farm/farm-1.png",
    mobileScreenshot: "/images/projects/farm/farm-2.png",
    skills: ["HTML", "CSS", "JavaScript", "Adobe Photoshop"],
    details: [
      "Responsive website built for a local farm. This was a refresh of an existing website. The goal was to bring the appearance and functionality more up to date, as well as make it responsive for mobile users.",
    ],
  },
  {
    id: 6,
    title: "Petsitting Service Website",
    description: "Mobile-first redesign for a local pet care business, modernizing the site's look and improving the experience for users on phones and tablets.",
    type: "Freelance",
    image: "/images/projects/petsitting/petsitting-1.png",
    link: "https://thegreatcrateescape.net/",
    screenshotType: "mixed",
    url: "thegreatcrateescape.net",
    desktopScreenshot: "/images/projects/petsitting/petsitting-1.png",
    mobileScreenshot: "/images/projects/petsitting/petsitting-2.png",
    skills: ["HTML", "CSS", "Tailwind CSS", "Adobe Photoshop"],
    details: [
      "A mobile-first update for a local petsitting business. Refreshed the look and rebuilt the layout to be responsive. Same site, just one that works on every screen now.",
    ],
  },
]
