export const recommendations = [
  {
    id: 1,
    quote: "Alissa is a talented front-end web developer that I have had the pleasure working with for about 10 years. She has a deep passion for crafting engaging, user-friendly web experiences. Her expertise extends to modern frameworks like React and Tailwind and brings a good eye for design with experience in tools like...",
    name: "Greg G.",
    role: "VP, Brand & Creative",
    initials: "GG",
    link: "https://www.linkedin.com/in/alissa-bengtson/details/recommendations/",
  },
  {
    id: 2,
    quote: "Alissa is an amazing collaborator and team mate. Working together at Corel, I was really impressed with how Alissa managed the large volume of work with creativity and poise. She is a great front-end dev and someone who really cares about the end product and user experience. Highly recommended.",
    name: "Jeremy P.",
    role: "Senior Web Producer",
    initials: "JP",
    link: null,
  },
  {
    id: 3,
    quote: "Alissa is a skilled front-end developer who consistently meets project expectations with efficiency and professionalism. Her ability to turn designs into responsive, user-friendly interfaces is impressive, and she delivers functional, well-structured code that aligns with project requirements...",
    name: "Delphine M.",
    role: "Director, Creative Services",
    initials: "DM",
    link: "https://www.linkedin.com/in/alissa-bengtson/details/recommendations/",
  },
  {
    id: 4,
    quote: "To put it simply, Alissa is an extremely talented front end developer. She created a variety of landing pages for my marketing campaigns — I was always impressed with what she produced. Engaging and smooth user experience every time.",
    name: "Rachel P.",
    role: "Customer Marketing Manager",
    initials: "RP",
    link: "https://www.linkedin.com/in/alissa-bengtson/details/recommendations/",
  },
  {
    id: 5,
    quote: "Alissa is an amazing web front end developer. Her design skills are extraordinary and she has a great work ethic. If you want the job done right, and to look great, then have Alissa do it.",
    name: "Frank W.",
    role: "Staff Software Engineer",
    initials: "FW",
    link: null,
  },
  {
    id: 6,
    quote: "Alissa is the rockstar web-producer behind several successful eDM campaigns at WinZip. Constantly provides high-quality content, on time and always on spec. Highly recommended.",
    name: "Lucas P.",
    role: "Online Marketing Campaign Manager",
    initials: "LP",
    link: null,
  },
]
